# Generated by Django 5.1 on 2024-08-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('book_author', models.CharField(max_length=100)),
                ('book_stock', models.IntegerField()),
                ('book_desc', models.TextField()),
                ('book_image', models.ImageField(upload_to='bookadd')),
            ],
        ),
    ]
