# Generated by Django 5.1 on 2024-08-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_head', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('book_name', models.CharField(max_length=100)),
                ('issue_name', models.CharField(max_length=100)),
                ('date_submm', models.CharField(max_length=100)),
            ],
        ),
    ]
