# Generated by Django 5.1 on 2024-08-31 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_head', '0002_issue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='issue_name',
            new_name='issue_date',
        ),
    ]
