# Generated by Django 5.1 on 2024-08-31 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_head', '0003_rename_issue_name_issue_issue_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookadd',
            name='book_image',
        ),
    ]
